"""Finished all models

Revision ID: db2a10e5281e
Revises: 
Create Date: 2024-03-25 20:43:48.253949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db2a10e5281e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('discord', sa.String(length=256), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'USER', 'READ_ONLY', name='roles'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('old_id', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('funds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('discord', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('old_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funds_id'), 'funds', ['id'], unique=False)
    op.create_table('managers_funds',
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('funds_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['funds_id'], ['funds.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('manager_id', 'funds_id')
    )
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('middlename', sa.String(length=64), nullable=True),
    sa.Column('gipsyteam', sa.Text(), nullable=True),
    sa.Column('pokerstrategy', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Text(), nullable=True),
    sa.Column('google', sa.Text(), nullable=True),
    sa.Column('mail', sa.Text(), nullable=True),
    sa.Column('vk', sa.Text(), nullable=True),
    sa.Column('facebook', sa.Text(), nullable=True),
    sa.Column('blog', sa.Text(), nullable=True),
    sa.Column('instagram', sa.Text(), nullable=True),
    sa.Column('forum', sa.Text(), nullable=True),
    sa.Column('neteller', sa.Text(), nullable=True),
    sa.Column('skrill', sa.Text(), nullable=True),
    sa.Column('ecopayz', sa.Text(), nullable=True),
    sa.Column('old', sa.Boolean(), nullable=True),
    sa.Column('fundName', sa.Text(), nullable=True),
    sa.Column('fund_id', sa.Integer(), nullable=True),
    sa.Column('nicknameOld', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('town', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('webmoney_id', sa.Text(), nullable=True),
    sa.Column('wallets', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('old_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_funds',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('funds_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['funds_id'], ['funds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'funds_id')
    )
    op.create_table('records_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('middlename', sa.String(length=64), nullable=True),
    sa.Column('gipsyteam', sa.Text(), nullable=True),
    sa.Column('pokerstrategy', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Text(), nullable=True),
    sa.Column('google', sa.Text(), nullable=True),
    sa.Column('mail', sa.Text(), nullable=True),
    sa.Column('vk', sa.Text(), nullable=True),
    sa.Column('facebook', sa.Text(), nullable=True),
    sa.Column('blog', sa.Text(), nullable=True),
    sa.Column('instagram', sa.Text(), nullable=True),
    sa.Column('forum', sa.Text(), nullable=True),
    sa.Column('neteller', sa.Text(), nullable=True),
    sa.Column('skrill', sa.Text(), nullable=True),
    sa.Column('ecopayz', sa.Text(), nullable=True),
    sa.Column('old', sa.Boolean(), nullable=True),
    sa.Column('fundName', sa.Text(), nullable=True),
    sa.Column('fund_id', sa.Integer(), nullable=True),
    sa.Column('nicknameOld', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('town', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('webmoney_id', sa.Text(), nullable=True),
    sa.Column('wallets', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('old_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['current_version_id'], ['records.id'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nicknames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_name', sa.String(length=64), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('history_record_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['history_record_id'], ['records_history.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nicknames')
    op.drop_table('records_history')
    op.drop_table('users_funds')
    op.drop_table('records')
    op.drop_table('managers_funds')
    op.drop_index(op.f('ix_funds_id'), table_name='funds')
    op.drop_table('funds')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
