version: '3'
services:
  reputationpg:
    restart: always
    image: 'postgres:latest'
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    networks:
      - my_network
  
  api:
    build:
      context: ./FastAPI
      dockerfile: Dockerfile
    command: sh -c "uvicorn app:app --host 0.0.0.0 --port 8000 --forwarded-allow-ips='*' --proxy-headers --reload"
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      API_SECRET: ${API_SECRET}
    restart: always
    depends_on:
      - reputationpg
    networks:
      - my_network
  
  client:
    build: 
      context: ./React
      dockerfile: Dockerfile
    depends_on:
      - api
    networks:
      - my_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfiile_nginx
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - api
      - client
    networks:
      - my_network

volumes:
  postgres:
  nginx:

networks:
  my_network: