version: '3'
services:
  reputationpg:
    restart: always
    image: 'postgres:latest'
    environment:
     -  POSTGRES_HOST=${POSTGRES_HOST}
     -  POSTGRES_USER=${POSTGRES_USER}
     -  POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     -  POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ':5479'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  api:
    build:
      context: ./FastAPI
      dockerfile: Dockerfile
    command: sh -c "uvicorn app:app --port 8000 --forwarded-allow-ips='*' --proxy-headers --reload"
    restart: always
    environment:
     -  POSTGRES_HOST=${POSTGRES_HOST}
     -  POSTGRES_USER=${POSTGRES_USER}
     -  POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     -  POSTGRES_DB=${POSTGRES_DB}
     -  API_SECRET=${API_SECRET}
    volumes:
      - './FastAPI:/app'
    depends_on:
      - reputationpg

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfiile_nginx
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      - api

volumes:
  postgres:
  nginx: