const Images = {
    logo: require('./logo.webp'),
    about: require('./navigation/about.webp'),
    home: require('./navigation/home.webp'),
    funds: require('./navigation/funds.webp'),
    trainer: require('./navigation/trainer.webp'),
    exit: require('./navigation/exit.webp'),
    homeBackground: require('./background/home__background.webp'),
    homeBackgroundMobile: require('./background/home__background-mobile.webp'),
    popup__background: require('./background/popup__background.webp'),
    table: require('./background/table.webp'),
    table__mobile: require('./background/table__mobile.webp'),
    advantages: require('./pictures/advantages.webp'),
    becking: require('./pictures/becking.webp'),
    education: require('./pictures/education.webp'),
    phone: require('./footer/phone.webp'),
    mail: require('./footer/mail.webp'),
    vk: require('./footer/vk.webp'),
    discord: require('./footer/discord.webp'),
    twitch: require('./footer/twitch.webp'),
    instagram: require('./footer/instagram.webp'),
    telegram: require('./footer/telegram.webp'),
    youtube: require('./footer/youtube.webp'),
    applefavicon: require('./favicons/apple-touch-icon.png'),
    applefavicon32: require('./favicons/favicon-32x32.png'),
    applefavicon16: require('./favicons/favicon-16x16.png'),
    applefaviconsaf: require('./favicons/safari-pinned-tab.svg'),
    add: require('./pictures/add.webp'),
    search: require('./pictures/search.webp'),
    arrow: require('./pictures/arrow.webp'),
}

export default Images