"""empty message

Revision ID: c0c333f8067f
Revises: 
Create Date: 2024-03-23 02:17:43.461343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0c333f8067f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('discord', sa.String(length=256), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'USER', 'READ_ONLY', name='roles'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('old_id', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('founds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('discord', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('old_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_founds_id'), 'founds', ['id'], unique=False)
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('by_fathers_name', sa.String(length=64), nullable=True),
    sa.Column('nicknames', sa.JSON(), nullable=True),
    sa.Column('gipsyteam', sa.Text(), nullable=True),
    sa.Column('pokerstrategy', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Text(), nullable=True),
    sa.Column('google', sa.Text(), nullable=True),
    sa.Column('mail', sa.Text(), nullable=True),
    sa.Column('vk', sa.Text(), nullable=True),
    sa.Column('facebook', sa.Text(), nullable=True),
    sa.Column('blog', sa.Text(), nullable=True),
    sa.Column('instagram', sa.Text(), nullable=True),
    sa.Column('forum', sa.Text(), nullable=True),
    sa.Column('lacation', sa.Text(), nullable=True),
    sa.Column('neteller', sa.Text(), nullable=True),
    sa.Column('skrill', sa.Text(), nullable=True),
    sa.Column('ecopayz', sa.Text(), nullable=True),
    sa.Column('webmoney', sa.JSON(), nullable=True),
    sa.Column('old', sa.Boolean(), nullable=False),
    sa.Column('fundName', sa.Text(), nullable=True),
    sa.Column('nicknameOld', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('old_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_records_id'), 'records', ['id'], unique=False)
    op.create_table('managers_founds',
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('founds_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['founds_id'], ['founds.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('manager_id', 'founds_id')
    )
    op.create_table('records_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('by_fathers_name', sa.String(length=64), nullable=True),
    sa.Column('nicknames', sa.JSON(), nullable=True),
    sa.Column('gipsyteam', sa.Text(), nullable=True),
    sa.Column('pokerstrategy', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Text(), nullable=True),
    sa.Column('google', sa.Text(), nullable=True),
    sa.Column('mail', sa.Text(), nullable=True),
    sa.Column('vk', sa.Text(), nullable=True),
    sa.Column('facebook', sa.Text(), nullable=True),
    sa.Column('blog', sa.Text(), nullable=True),
    sa.Column('instagram', sa.Text(), nullable=True),
    sa.Column('forum', sa.Text(), nullable=True),
    sa.Column('lacation', sa.Text(), nullable=True),
    sa.Column('neteller', sa.Text(), nullable=True),
    sa.Column('skrill', sa.Text(), nullable=True),
    sa.Column('ecopayz', sa.Text(), nullable=True),
    sa.Column('webmoney', sa.Text(), nullable=True),
    sa.Column('old', sa.Boolean(), nullable=False),
    sa.Column('fundName', sa.Text(), nullable=True),
    sa.Column('nicknameOld', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('old_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['current_version'], ['records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_records_history_id'), 'records_history', ['id'], unique=False)
    op.create_table('users_founds',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('founds_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['founds_id'], ['founds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'founds_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_founds')
    op.drop_index(op.f('ix_records_history_id'), table_name='records_history')
    op.drop_table('records_history')
    op.drop_table('managers_founds')
    op.drop_index(op.f('ix_records_id'), table_name='records')
    op.drop_table('records')
    op.drop_index(op.f('ix_founds_id'), table_name='founds')
    op.drop_table('founds')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
