version: '3'
services:
  reputationpg:
    restart: always
    image: 'postgres:latest'
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  
  api:
    build: .
    container_name: startme-reputation
    command: sh -c "python db/wait_for_db.py  &&
                    uvicorn app:app --host 0.0.0.0 --port 8000"
    ports:
      - '8000:8000'
    restart: always
    env_file:
      - .env


volumes:
  postgres:
    
