version: '3'
services:
  reputationpg:
    restart: always
    image: 'postgres:latest'
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  api:
    build: .
    image: glitchcode/startme-repo:1.1
    command: sh -c "alembic upgrade head && uvicorn app:app --host 0.0.0.0 --port 8000"
    ports:
      - '8000:8000'
    restart: always
    env_file:
      - .env
    depends_on:
      - reputationpg

volumes:
  postgres:


